package View;

import Controller.EmissaoContaDAO;
import Controller.PessoaEnderecoDAO;
import Model.EmissaoConta;
import Model.PessoaEndereco;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

public class DialogImprimirConta extends javax.swing.JDialog {

    private EmissaoContaDAO dao = new EmissaoContaDAO();
    private EmissaoConta conta = new EmissaoConta();
    
    private PessoaEnderecoDAO daoEndereco = new PessoaEnderecoDAO();
    private PessoaEndereco endereco = new PessoaEndereco();


    private SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    private int id = 0;

    private void iniciaComponentes() {

        this.conta = dao.get(EmissaoConta.class, this.id);
        this.endereco = daoEndereco.get(PessoaEndereco.class, this.conta.getCliente().getId());
        
        textArea.append("############## EMPRESA DE ÁGUA ##############");
        textArea.append("\nNome do cliente: ");
        textArea.append(this.conta.getCliente().getNome());

        textArea.append("\nEndereço do cliente: ");
        if(this.endereco != null){
        textArea.append(this.endereco.getNome() + ", " + this.endereco.getNumero() + 
                ", " + this.endereco.getBairro() + ", " + this.endereco.getCidade().getNome());    
        }
        
        textArea.append("\nNome do funcionario: ");
        textArea.append(this.conta.getFuncionario().getNome());

        textArea.append("\nMedição mês passado: ");
        textArea.append(this.conta.getVlRelogioMesPassado().toString() + "Kw/h");

        textArea.append("\nMedição mês atual: ");
        textArea.append(this.conta.getVlRelogioMesAtual().toString() + " Kw/h");
        
        textArea.append("\nData aferição: ");
        textArea.append(formato.format(this.conta.getDtAfericao()));

        textArea.append("\nTarifa mês: ");
        textArea.append("R$" + this.conta.getVlTarifaMes().setScale(2, RoundingMode.DOWN).toString());
        
        
                
        textArea.append("\nTotal a pagar: ");
        textArea.append("R$" + this.conta.getVlTotal().setScale(2, RoundingMode.DOWN).toString());

    }

    public DialogImprimirConta(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();
        this.id = Integer.parseInt(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de endereços das pessoas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.iniciaComponentes();

    }//GEN-LAST:event_formWindowOpened

    private void fillComponents(EmissaoConta emissaoConta) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogImprimirConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogImprimirConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogImprimirConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogImprimirConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogImprimirConta dialog = new DialogImprimirConta(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
